name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish HIVTreatmentSystem.API/HIVTreatmentSystem.API.csproj -c Release -o ./publish

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: ./publish
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          promote: true 